### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by cwb4** [yasoob/practical-python-projects#1]
Hi — two questions

1. Does book come in ePub format or only pdf?

1. Is there a companion github site with code by chapter.

Thanks

cwb4@mac.com

**Comment by yasoob** [comment]
Hi @cwb4 

Thank you so much for asking these important questions.

1. For now it is only in PDF. The EPUB and MOBI will be launched in a couple of days. If you buy the PDF now, you will get the EPUB and MOBI for free once they are released.
2. We have the code for each project. I will be polishing it and publishing it in this repo.  

If you have any other questions, please feel free to create a new issue or reopen this one :)

**Comment by cwb4** [comment]
Hi — thanks for reply.  Look forward to ePub version & example repo.

**Comment by cwb4** [comment]
Hi — checking back in to see if ePub version is available?

**Comment by yasoob** [comment]
@cwb4 the EPUB is 95% ready. I will be giving it another pass during the next couple of days. If everything goes well it will be live in less than a week :)

**Comment by cwb4** [comment]
Hi -- any progress on epub version?

**Comment by yasoob** [comment]
@cwb4 the EPUB and MOBI versions are ready and will be sent out to the people later today. The code for each project has also been uploaded in this GitHub repo. :)

**Comment by cwb4** [comment]
Perfect, thanks.
