### ISSUE TITLE
Missing a $ symbol

### ISSUE THREAD

**Issue by jalvaradosegura** [yasoob/practical-python-projects#14]
## Location Within the Book

* Book order number: 10275 (not sure if this point is correct)
* Book build date: First Edition, 2020-09-23-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 3
* Section: 5

Page: 38
Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 
Here in this section we are replacing the variables declared in the .py file within the .html file.

When we get to the item-charge (line 16) variable, there is a $ symbol missing. This symbol is added a few pages later, when the whole code is being showed. Im not sure if this was done on purpose, but i find very hard to spot that little difference while watching to the whole code

```html
10 {% for item in items %}
11 <tr class="item">
12 <td>
13 {{item['title']}}
14 </td>
15 <td>
16 {{item['charge']}}
17 </td>
18 </tr>
19 {% endfor %}
```

## Possible Solutions
Add the symbol before showing the whole code

```html
10 {% for item in items %}
11 <tr class="item">
12 <td>
13 {{item['title']}}
14 </td>
15 <td>
16 ${{item['charge']}}
17 </td>
18 </tr>
19 {% endfor %}
```

**Comment by yasoob** [comment]
Hey Jorge, so sorry for such a delayed update. COVID had me struggling for a bit but this bug is fixed in the latest version that will go out soon. Thanks ❤️
