### ISSUE TITLE
Missing parentheses in a print

### ISSUE THREAD

**Issue by jalvaradosegura** [yasoob/practical-python-projects#15]
## Location Within the Book

* Book order number: 10275
* Book build date: First Edition, 2020-09-23-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 6
* Section: 3

Page: 100
Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 
There are missing parentheses in the last print, line 56 of the code block on that page ([Line 73 on this code snippet](https://github.com/yasoob/practical-python-projects/blob/master/code-listings/chapter_6/Example_02.py)).
```py
55 if r.status_code != requests.codes.ok:
56     print r.text
```

## Possible Solutions
Add the parentheses

**Comment by yasoob** [comment]
Hey Jorge, so sorry for such a delayed update. COVID had me struggling for a bit but this bug is fixed in the latest version that will go out soon. Thanks ❤️
