### ISSUE TITLE
Missing host and port in the app.run results in an error when deploying to Heroku

### ISSUE THREAD

**Issue by jalvaradosegura** [yasoob/practical-python-projects#16]
## Location Within the Book

* Book order number: 10275
* Book build date: First Edition, 2020-09-23-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 6
* Section: 3

Page: 100
Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 
After doing the deploy to Heroku (Page 103), i was getting this error :

```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

Following this [answer](https://stackoverflow.com/questions/17260338/deploying-flask-with-heroku), the problem got fixed.  The problem was that the [code](https://github.com/yasoob/practical-python-projects/blob/master/code-listings/chapter_6/Example_02.py) is missing the host and the port (line 75 of the code snippet, line 59 in the book).

```py
# Copied from the book (page 100)
58 if __name__ == '__main__':
59     app.run()
```

## Possible Solutions
Add the host and port parameters

```py
# The code i copied and worked for me
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)

> I noticed this error when i was doing section 6.4, when i was trying to create the webhook

```

**Comment by yasoob** [comment]
Hey @jalvaradosegura thank you so much for all the bug reports. I will be going over them over the weekend and making sure they are fixed in the next release. I will close these issues once I get the fixes in. :)

**Comment by jalvaradosegura** [comment]
Hey @yasoob! Im happy to be able to contribute :)

**Comment by jalvaradosegura** [comment]
Hey @yasoob! Im very happy to be able to contribute to the book in this way. Is the first time i do something like this, i find it very cool.

Thanks for the book!

**Comment by jalvaradosegura** [comment]
Hey @yasoob! Im very happy to be able to contribute to the book in this way. Is the first time i do something like this, i find it very cool.

Thanks for the book!

**Comment by yasoob** [comment]
Hey Jorge, so sorry for such a delayed update. COVID had me struggling for a bit but this bug is fixed in the latest version that will go out soon. Thanks ❤️
