### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by PeterHuynh** [yasoob/practical-python-projects#17]
## Location Within the Book

* Book order number: 10380
* Book build date (It is in the page footer for the latest PDF version and on page 1 for the MOBI + EPUB versions): Build: 2020-09-23-alpha.
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 3
* Section:3.4

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

I run the app.py on windows10 and need to import os 
```
If code-related, enter it within these backticks. Otherwise, delete this segment.

\app.py", line 13, in <module>
    port = int(os.environ.get("PORT", 5000))
NameError: name 'os' is not defined
```

## Possible Solutions
import os in app.py
## Your full name so I can provide accurate credit within the book
Peter Huynh

**Comment by yasoob** [comment]
Hey Peter, so sorry for such a delayed update. COVID had me struggling for a bit but this bug is fixed in the latest version that will go out soon. Thanks ❤️
