### ISSUE TITLE
Typo strftime("%B %-d, %Y")

### ISSUE THREAD

**Issue by PeterHuynh** [yasoob/practical-python-projects#18]
## Location Within the Book

* Book order number: 10380
* Book build date (It is in the page footer for the latest PDF version and on page 1 for the MOBI + EPUB versions):2020-09-23-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter:3
* Section:3.5

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

    today = today.strftime("%B %-d, %Y")
ValueError: Invalid format string
```
If code-related, enter it within these backticks. Otherwise, delete this segment.
today = datetime.today().strftime("%B %-d, %Y")

```

## Possible Solutions
 today = datetime.today().strftime("%B - %d, %Y")
## Your full name so I can provide accurate credit within the book
Peter Huynh

**Comment by yasoob** [comment]
Hey Peter, so sorry for such a delayed update. COVID had me struggling for a bit but this bug is fixed in the latest version that will go out soon. Thanks ❤️
