### ISSUE TITLE
The link to download_trailers.py isn't commit/tag pinned

### ISSUE THREAD

**Issue by treyhunner** [yasoob/practical-python-projects#2]
The link to the `download_trailers.py` file goes to the master branch. But the master branch seems to use a newer version of the code (there's a required `download_all_urls` argument).

Two recommendations:

- Pin the URLs to GitHub for a specific commit or tag. For example https://github.com/aag/apple_trailer_downloader/blob/v1.0.0-beta/download_trailers.py instead of https://github.com/aag/apple_trailer_downloader/blob/master/download_trailers.py
- Maybe update that `download_trailers.py` file if the newer version is better

Very neat book. Thanks for writing it @yasoob!

**Comment by yasoob** [comment]
Good catch @treyhunner! I will make sure it is updated in the book. Will keep this issue open until it is fixed. Thanks :)

**Comment by yasoob** [comment]
This issue has been fixed in the latest version that will be sent out later today. I ended up updating my code to make use of the new download_trailers.py file and also used the tagged version this time. Thanks again @treyhunner!
