### ISSUE TITLE
11.2.1 grammar/word choice

### ISSUE THREAD

**Issue by brotherchris65** [yasoob/practical-python-projects#20]
## Location Within the Book

* Book order number: 11306
* Book build date: Build: 2020-09-23-alpha.
* Book format (PDF, Epub or Mobi): PDF
* Chapter:11
* Section: 11.2.1

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

> This is used to send emails from a client to a server and **from** relaying messages from one server to the next. The second from should read "for"

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

## Possible Solutions
Change word from to for
## Your full name so I can provide accurate credit within the book
Chris Hill

**Comment by yasoob** [comment]
Hey Chris, so sorry for such a delayed update. COVID had me struggling for a bit but this bug is fixed in the latest version that will go out soon. Thanks ❤️
