### ISSUE TITLE
Invoice Generator - app_test.py - [Errno 61]

### ISSUE THREAD

**Issue by JRD8** [yasoob/practical-python-projects#28]
## Location Within the Book

* Book order number: 23632316
* Book build date (It is in the page footer for the latest PDF version and on page 1 for the MOBI + EPUB versions): 2021-02-27-rc
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 3
* Section: 7

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

Cheers and love this book so far.  Have been working through the Invoice Generator project, no problem,  At last step, running app.py works fine and can verify in browser.  However, once creating and running app_test.py, there's some sort of new connection problem "Failed to establish a new connection: [Errno 61] Connection refused')" and won't generate the PDF invoice.  I have also attached screenshot of terminal error report.

Have checked app_test.py code and is identical to you code same in book.

Wondering if there's a solution to this? 
```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

## Possible Solutions

Have Googled this error and appears that it could be firewall related.  However, app.py is running fine through the firewall, while app_test.py does not.  Please let me know thoughts.  Thanks. - JRD
<img width="1263" alt="Screen Shot 2021-03-28 at 3 13 04 PM" src="https://user-images.githubusercontent.com/4774517/112764979-eef9fa80-8fd8-11eb-936f-dbe8f589e578.png">

**Comment by yasoob** [comment]
Hi @JRD8, 

Can you show me the code of your `app_test.py` file?

**Comment by JRD8** [comment]
Certainly.  Apologies in advance if any typos - although I don’t believe so.
