### ISSUE TITLE
FIFA Twilio Bot - Security Risk/Warnings With worldcup.sfg.io Website?

### ISSUE THREAD

**Issue by JRD8** [yasoob/practical-python-projects#29]
## Location Within the Book

* Book order number: 23632316
* Book build date (It is in the page footer for the latest PDF version and on page 1 for the MOBI + EPUB versions): 2021-02-27-rc.
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 4
* Section: 3

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

FYI.  3 major browsers (Firefox, Chrome, Safari) are all currently returning *security risks*/warnings accessing and using worldcup.sfg.io.  

Would love to do this project, but believe it will be security risk on my laptop.  Should we be proceeding?  Is there possible work-around/alternate  safe site to use that you recommend?

## Your full name so I can provide accurate credit within the book
James Diener
<img width="1280" alt="Screen Shot 2021-03-28 at 4 01 57 PM" src="https://user-images.githubusercontent.com/4774517/112766360-721e4f00-8fdf-11eb-80c8-7fe421b6fac3.png">
<img width="1278" alt="Screen Shot 2021-03-28 at 4 01 15 PM" src="https://user-images.githubusercontent.com/4774517/112766361-734f7c00-8fdf-11eb-9568-0dce2b3b4815.png">
<img width="1278" alt="Screen Shot 2021-03-28 at 4 00 51 PM" src="https://user-images.githubusercontent.com/4774517/112766365-764a6c80-8fdf-11eb-9e08-c0e1bdc9a6b0.png">

**Comment by yasoob** [comment]
Hi @JRD8 it should be perfectly fine to proceed. You will not be inputting any sensitive information on the website. You will just be getting the JSON and printing it on screen. There should not be a security risk because of that in this particular project. :)

**Comment by JRD8** [comment]
Yasoob:

Thank you for quick response.

However, please note that since the website's security certificate has expired, running the .py program from terminal = complains and returns an error/quits.

Not sure if it’s a setting/option on my laptop that I can deactivate, but default security setting on laptop (Mac OS X Big Sur 11.2.2) won’t let me (and presumably some other users) proceed.  

See screen shot with error returned with just the initial get requests (for example).

**Comment by yasoob** [comment]
@JRD8 Can you try using `http` instead of `https` in the URL and let me know if the problem still persists? This is for the Python code.

**Comment by JRD8** [comment]
That solved it.  Works perfectly now.  Thank you for quick response!

Best,

JRD
