### ISSUE TITLE
Possible incorrect file name typo.

### ISSUE THREAD

**Issue by tamerz** [yasoob/practical-python-projects#31]
## Location Within the Book

* Book order number: Is this the "Transaction" number?
* Book build date: 2021-02-27-rc
* Book format: PDF
* Chapter: 3
* Section: 3.3

## Description 

> invoice.pdf:

## Possible Solutions
Small issue, but it says `invoice.pdf` for the file name of some Python code. Perhaps it was meant to say `invoice.py`?

## Your full name so I can provide accurate credit within the book
Tames McTigue

**Comment by yasoob** [comment]
I looked through the text and couldn't find it. If you can maybe provide me with a screenshot of the error I can fix it and give you credit. Till then I am closing this issue.
