### ISSUE TITLE
Fig. 7.2 screenshot no longer matches The Movie DB website

### ISSUE THREAD

**Issue by audreyfeldroy** [yasoob/practical-python-projects#5]
## Location within the Book

* Book build date (the date on page 1): 2020-08-20-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 7
* Section: 7.3

## Description 

The screenshot of TMDb says to click on "SIGN UP". 

## Possible Solutions

The website has changed: the link to click on is "Join TMDb".

## Your full name so I can provide accurate credit within the book

Audrey Feldroy

**Comment by yasoob** [comment]
I have updated the images in the latest update to reflect the change in TMDb's website. Thanks for bringing this up! :)
