### ISSUE TITLE
Issue template asks for "the date on page 1" which is confusing

### ISSUE THREAD

**Issue by audreyfeldroy** [yasoob/practical-python-projects#6]
## Location 

The issue template:
https://github.com/yasoob/practical-python-projects/blob/master/ISSUE_TEMPLATE

## Description 

The issue template asks the reader to provide:

> Book build date (the date on page 1)

Page 1 is the cover. It's unclear what to provide from here.

## Possible Solutions

I like option 2. @pydanny and @yasoob, thoughts?

Option 1:

> Book build date (the date from the book's filename)

Option 2:

> Book version (the date from the book's filename)

Option 3:

> Book version (the date and version name from the interior matter on page 3, e.g. *2020-08-20-alpha*)

## Your full name so I can provide accurate credit within the book

Audrey Feldroy

**Comment by audreyfeldroy** [comment]
@pydanny suggests adding the build date to the footer. 

Then the issue template would say something like:

> Book version from the page footer, e.g. 2020-09-01-alpha

**Comment by yasoob** [comment]
This issue has been fixed in the latest update that will be sent out later today. I have added the build date in the PDF footer and have also updated the `ISSUE_TEMPLATE` to reflect that change.
