### ISSUE TITLE
Section 3.1 Setting up the project

### ISSUE THREAD

**Issue by smithers** [yasoob/practical-python-projects#7]
## Location Within the Book

* Book build date (the date on page 1):First Edition, 2020-08-20-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter:3
* Section:3.1

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

```
Line 3 of "Setting up the project", should be:    3   $  python -m venv env

```

## Your full name so I can provide accurate credit within the book
Jeff Czarniak

**Comment by yasoob** [comment]
Good catch. Latest version should have this fixed. You will hopefully receive it later today :)
