### ISSUE TITLE
Code Error 3.6

### ISSUE THREAD

**Issue by smithers** [yasoob/practical-python-projects#8]
## Location Within the Book

* Book build date (the date on page 1): 2020-08-20-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 3
* Section: 6

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

```
line 12: argument given to html.write_pdf() should be 'path/invoice.pdf', not 'path/invoice.html'
```

## Your full name so I can provide accurate credit within the book
Jeff Czarniak

**Comment by yasoob** [comment]
Thank you so much for the bug report @smithers :) I will fix that in the next version.

**Comment by yasoob** [comment]
This issue has been fixed in the latest update that will be sent out later today. Thanks again @smithers!
