### ISSUE TITLE
Further clarification needed for 3.7

### ISSUE THREAD

**Issue by smithers** [yasoob/practical-python-projects#9]
## Location Within the Book

* Book build date (the date on page 1):First Edition, 2020-08-20-alpha
* Book format (PDF, Epub or Mobi): PDF
* Chapter: 3
* Section: 7

Hint: Page numbers change all the time. The best way to report an issue is by chapter and section numbers.

## Description 

```
I am at a loss re what to do with the page of code given that begins with:
1 import requests 
2
3 url = 'http://127.0.0.1:5000/'

I realize it's testing the json request, but can't tell if the code is supposed to be added to app.py, or run as a separate script?  I think it's the former, as I see no request in app.py to open up 127.0.0.1.  More instruction here would be very helpful.  Thanks.
```

**Comment by yasoob** [comment]
Hi @smithers 

That piece of code is just there to test whether our Flask web app is working and responding the way we expect/want it to. This is a separate file and will be run independently from our `app.py` file. I will add more details in the book to make it clearer. If there is anything else in this section that was unclear let me know.

Thanks for bringing this up :)

**Comment by yasoob** [comment]
I have added some more context to this code in the book and made sure people are aware of what we are doing with it.
